[Unit]
Description=VSER29 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER29.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/13

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER29.conf /dev/tcu-muxer/cpu1/13
SyslogIdentifier=VSER29-console-server
Restart=always
