[Unit]
Description=VSER5 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER5.conf
ConditionPathExists=/dev/tcu-muxer/cpu0/5

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER5.conf /dev/tcu-muxer/cpu0/5
SyslogIdentifier=VSER5-console-server
Restart=always
