[Unit]
Description=VSER30 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER30.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/14

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER30.conf /dev/tcu-muxer/cpu1/14
SyslogIdentifier=VSER30-console-server
Restart=always
