[Unit]
Description=VSER7 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER7.conf
ConditionPathExists=/dev/tcu-muxer/cpu0/7

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER7.conf /dev/tcu-muxer/cpu0/7
SyslogIdentifier=VSER7-console-server
Restart=always
