[Unit]
Description=VSER23 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER23.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/7

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER23.conf /dev/tcu-muxer/cpu1/7
SyslogIdentifier=VSER23-console-server
Restart=always
