[Unit]
Description=VSER16 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER16.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/0

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER16.conf /dev/tcu-muxer/cpu1/0
SyslogIdentifier=VSER16-console-server
Restart=always
