[Unit]
Description=VSER0 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER0.conf
ConditionPathExists=/dev/tcu-muxer/cpu0/0

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER0.conf /dev/tcu-muxer/cpu0/0
SyslogIdentifier=VSER0-console-server
Restart=always
