[Unit]
Description=VSER8 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER8.conf
ConditionPathExists=/dev/tcu-muxer/cpu0/8

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER8.conf /dev/tcu-muxer/cpu0/8
SyslogIdentifier=VSER8-console-server
Restart=always
