[Unit]
Description=VSER25 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER25.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/9

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER25.conf /dev/tcu-muxer/cpu1/9
SyslogIdentifier=VSER25-console-server
Restart=always
