[Unit]
Description=VSER2 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER2.conf
ConditionPathExists=/dev/tcu-muxer/cpu0/2

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER2.conf /dev/tcu-muxer/cpu0/2
SyslogIdentifier=VSER2-console-server
Restart=always
