[Unit]
Description=VSER19 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER19.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/3

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER19.conf /dev/tcu-muxer/cpu1/3
SyslogIdentifier=VSER19-console-server
Restart=always
