[Unit]
Description=VSER21 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER21.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/5

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER21.conf /dev/tcu-muxer/cpu1/5
SyslogIdentifier=VSER21-console-server
Restart=always
