[Unit]
Description=VSER31 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER31.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/15

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER31.conf /dev/tcu-muxer/cpu1/15
SyslogIdentifier=VSER31-console-server
Restart=always
