[Unit]
Description=VSER24 Console Server
ConditionPathExists=/etc/obmc-console/server.VSER24.conf
ConditionPathExists=/dev/tcu-muxer/cpu1/8

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.VSER24.conf /dev/tcu-muxer/cpu1/8
SyslogIdentifier=VSER24-console-server
Restart=always
