#!/bin/bash

# shellcheck source=meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/catalina/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

host_power_on
ret=$?

if [ $ret -ne 0 ]; then
   log_msg="host power on failed"
   phosphor_log_err "$log_msg"
   exit 1
fi

exit 0
