#!/bin/bash
# shellcheck source=meta-facebook/meta-yosemite5/recipes-yosemite5/plat-tool/files/yosemite5-common-functions
source /usr/libexec/yosemite5-common-functions

echo "initial value for GPIO output pins"
# set initial value for GPIO output pins

# A0-A7
# B0-B7
# D0-D7
# E0-E7
# F0-F7
# G0-G7
# H0-H7
# I0-I7
# M0-M7
# N0-N7
# O0-O7
# P0-P7
# Q0-Q7
# R0-R7
# S0-S7
# T0-T7
# U0-U7
# V0-V7

get_gpio FM_BMC_MUX1_SEL
get_gpio FM_DEBUG_PORT_PRSNT_N
get_gpio BMC_ID_BEEP_SEL
get_gpio BMC_JTAG_MUX_SEL
get_gpio IRQ_PCH_TPM_SPI_LV3_N
get_gpio USB_OC0_REAR_N
get_gpio SPI_BMC_BIOS_ROM_IRQ0_N
get_gpio SMB_BMC_TMP_ALERT
get_gpio FM_BMC_PROT_LS_EN
get_gpio AC_PWR_BMC_BTN_N
get_gpio LED_POSTCODE_0
get_gpio LED_POSTCODE_1
get_gpio LED_POSTCODE_4
get_gpio PSU_SMB_ALERT
get_gpio FM_TPM_PRSNT_0_N
get_gpio IRQ_TPM_SPI_N
get_gpio FM_BOARD_BMC_REV_ID0
get_gpio FM_BOARD_BMC_REV_ID1
get_gpio FM_BOARD_BMC_REV_ID2

get_gpio FM_BMC_DBP_PRESENT_N
get_gpio L2_RST_REQ_OUT
get_gpio L0L1_RST_REQ_OUT
get_gpio BMC_I2C0_FPGA_ALERT
get_gpio UART_MUX_SEL
get_gpio I2C_MUX_RESET
get_gpio RSVD_NV_PLT_DETECT
get_gpio SPI_TPM_INT
get_gpio CPU_JTAG_MUX_SELECT
get_gpio THERM_BB_OVERT
get_gpio THERM_BB_WARN
get_gpio SPI_BMC_FPGA_INT
get_gpio CPU_BOOT_DONE
get_gpio PMBUS_GNT
get_gpio CHASSIS_PWR_BRK
get_gpio PCIE_WAKE
get_gpio PDB_THERM_OVERT
get_gpio SHDN_REQ
get_gpio PWR_LED_N
get_gpio PSU_FW_UPDATING_N
get_gpio DEBUG_CARD_BYPASS
get_gpio FM_FLASH_LATCH_N
get_gpio IOEXP_INT_3V3
get_gpio SYS_FAULT_LED_N
get_gpio RUN_POWER_FAULT

# set initial value for IOEXP GPIO output pins

# MB IOEXP
set_gpio FM_CLKMUX_0_SEL 1
set_gpio FM_CLKMUX_1_SEL 1
set_gpio FM_CLKMUX_2_SEL 1
set_gpio FM_CLKMUX_3_SEL 1
set_gpio FM_CLKGEN_GPIO2 1
set_gpio FM_CLKGEN_GPIO4 0
set_gpio RST_USB_HUB_0_N 1

# SGPIO
set_gpio SGPIO_RSTBTN_OUT 0
set_gpio IBB_BMC_SRST 1
set_gpio FM_I3C_SPD_AH_SEL_R 0
set_gpio FM_I3C_SPD_IP_SEL_R 0
set_gpio FM_JTAG_BMC_MUX_S0_R 0
set_gpio FM_JTAG_BMC_MUX_S1_R 0
set_gpio FM_JTAG_BMC_OE_1_R_N 1
set_gpio FM_JTAG_BMC_OE_R_N 1
set_gpio FM_REMOTEJTAG_EN_R_N 1
set_gpio FM_CPU_FORCE_SELFREFRESH_R 0
set_gpio FM_CPU_NMI_SYNC_FLOOD_R_N 1
set_gpio FM_CPU_TRIGGERTSC_OE_R_N 1
set_gpio FM_PASSWORD_CLEAR_R_N 1
set_gpio FM_BIOS_USB_RECOVERY_N 1
set_gpio FM_USB_MUX_OE_R_N 1
set_gpio FM_USB_MUX_SEL_R 0
set_gpio RST_SMB_BOOT_R_N 1
set_gpio RST_SMB_MCIO0A_R_N 1
set_gpio RST_SMB_NIC_R_N 1
set_gpio FM_PPS_NIC_IN_BUF_OE_R_N 1
set_gpio FM_PPS_NIC_IN_EN_R 0
set_gpio FM_PPS_NIC_IN_OE_R_N 1
set_gpio FM_PPS_NIC_IN_S0_R 0
set_gpio FM_PPS_NIC_IN_S1_R 0
set_gpio FM_PPS_NIC_OUT_BUF_OE_R_N 1
set_gpio FM_PPS_NIC_OUT_CPU_OE_R_N 1
set_gpio FM_PPS_NIC_OUT_EN_R 0
set_gpio JTAG_CPLD_DBREQ_R_N 1
set_gpio HDT_HDR_RESET_R_N 1
set_gpio FM_SMB_AUTH_MUX_OE_R_N 1
set_gpio FM_SCM_LED_R_N 1
set_gpio SGPIO_BMC_READY 1

echo 1 > /sys/class/leds/bmc_ready_noled/brightness

exit 0
